Fix possibly conflict artifact names
Say, build with `srcs = ["kernel.cu", "nested/kernel.cu"]` will result:

```
MandatoryInputs: Attempted action contains artifacts not in previous action (first 5):
        basic/nested/kernel.cu
Previous action contains artifacts not in attempted action (first 5):
        basic/kernel.cu
Outputs: are equal
ERROR: /home/cloud/rules_cuda/examples/basic/BUILD.bazel:5:13: for basic/_objs/kernel/kernel.o, previous action: action 'Compiling basic/kernel.cu', attempted action: action 'Compiling basic/nested/kernel.cu'
```

This changes to use basename indices to deduplicate as in cc rules.