Fix MODULE example in README
The previous example in README failed with error:

```
ERROR: Analysis of target '//project_template/cpp:main' failed; build aborted: The module extension defined at /home/dev/.cache/bazel/_bazel_dev/0a671fc952be90f724e819c56b1dda7d/external/rules_cuda+/cuda/extensions.bzl:42:29 does not have a tag class named toolkit, but its use is attempted at /home/dev/llm/MODULE.bazel:4:13
```

we have to import toolkit instead of toolchain from cuda.